#!/usr/bin/env python3
"""Scaffold a JasperReports 7 style template (.jrtx) from a color palette.

A style template is a standalone XML file (root <jasperTemplate>) holding a set
of named <style> elements. A report references it once with a <template>
expression (see scaffold_jrxml.py --style-template), and every report that
references the same .jrtx then shares one centrally-managed look -- change the
.jrtx, redeploy it, and every consuming report restyles. This is the JR-native
way to share styling across many reports instead of repeating inline colors.

The emitted styles use the SAME palette keys as scaffold_jrxml.py's THEMES (we
import that dict), so a style template and an inline --template look match. The
style NAMES follow a fixed convention the scaffolder also references:
    jdBase (isDefault), jdTitle, jdSubtitle, jdColumnHeader, jdDetail,
    jdGroupHeader, jdGroupFooter, jdPageFooter
jdBase is the report's default style (sets fontName + base size/color for every
text element that does not override it), so attaching the template visibly
restyles a report even with no other change.

JR7-native: style attributes are flattened (fontSize, bold, forecolor,
hTextAlign, vTextAlign) -- not a 6.x <reportElement>/<font> nesting.
"""
import argparse
import os
import sys
from xml.sax.saxutils import escape

# reuse the exact palettes scaffold_jrxml.py ships, so looks line up
from scaffold_jrxml import THEMES, DEFAULT_THEME

# fixed style names: emitted here, referenced by scaffold_jrxml.py --use-template-styles
STYLE_NAMES = ["jdBase", "jdTitle", "jdSubtitle", "jdColumnHeader", "jdDetail",
               "jdGroupHeader", "jdGroupFooter", "jdPageFooter"]


def style_el(name, *, default=False, font=None, size=None, bold=False,
             forecolor=None, backcolor=None, halign=None, valign=None):
    attrs = [f'name="{escape(name)}"']
    if default:
        # JR7 parses the .jrtx with strict Jackson (like .jrdax): the bean
        # property is "default", NOT the 6.x XML "isDefault" (a wrong name throws
        # UnrecognizedPropertyException at fill time, surfaced as a 400).
        attrs.append('default="true"')
    if font:
        attrs.append(f'fontName="{escape(font)}"')
    if size is not None:
        attrs.append(f'fontSize="{size}"')
    if bold:
        attrs.append('bold="true"')
    if forecolor:
        attrs.append(f'forecolor="{forecolor}"')
    if backcolor:
        attrs.append(f'mode="Opaque" backcolor="{backcolor}"')
    if halign:
        attrs.append(f'hTextAlign="{halign}"')
    if valign:
        attrs.append(f'vTextAlign="{valign}"')
    return f'\t<style {" ".join(attrs)}/>'


def build_jrtx(palette: str, font: str, base_size: float) -> str:
    t = THEMES.get(palette or DEFAULT_THEME, THEMES[DEFAULT_THEME])
    out = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<!-- Generated by jasper-deploy scaffold_style_template.py. '
           'JR7-native style template. -->',
           '<jasperTemplate>']
    # default style: applies fontName + base color/size to all unstyled text
    out.append(style_el("jdBase", default=True, font=font, size=base_size,
                        forecolor="#222222"))
    out.append(style_el("jdTitle", font=font, size=t["title_size"], bold=True,
                        forecolor=t["title_fg"], valign="Middle"))
    out.append(style_el("jdSubtitle", font=font, size=9.0,
                        forecolor=t["subtitle_fg"]))
    # column header: filled themes paint the band; a None header_bg (minimal)
    # leaves the cell unfilled (dark text only).
    out.append(style_el("jdColumnHeader", font=font, size=9.0, bold=True,
                        forecolor=t["header_fg"],
                        backcolor=t["header_bg"], valign="Middle"))
    out.append(style_el("jdDetail", font=font, size=8.0, valign="Middle"))
    out.append(style_el("jdGroupHeader", font=font, size=9.0, bold=True,
                        forecolor=t["group_fg"], backcolor=t["group_bg"],
                        valign="Middle"))
    out.append(style_el("jdGroupFooter", font=font, size=8.0, bold=True,
                        valign="Middle"))
    out.append(style_el("jdPageFooter", font=font, size=8.0,
                        forecolor=t["footer_fg"]))
    out.append('</jasperTemplate>')
    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description="Scaffold a JR7 .jrtx style template.")
    ap.add_argument("--name", required=True, help="style template name (no spaces)")
    ap.add_argument("--out", help="output .jrtx path (default: <name>.jrtx)")
    ap.add_argument("--palette", default=DEFAULT_THEME, choices=list(THEMES),
                    help=f"color palette (shared with scaffold_jrxml --template; default {DEFAULT_THEME})")
    ap.add_argument("--font", default="SansSerif",
                    help="font family for every style (default SansSerif, a Java "
                         "logical font always present; use an extension font name "
                         "only if it is registered on the JRS classpath)")
    ap.add_argument("--base-size", type=float, default=8.0,
                    help="base (default-style) font size in pt (default 8.0)")
    args = ap.parse_args()

    out_path = args.out or f"{args.name}.jrtx"
    xml = build_jrtx(args.palette, args.font, args.base_size)
    os.makedirs(os.path.dirname(os.path.abspath(out_path)), exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(xml)
    print(f"wrote {out_path} (palette={args.palette}, font={args.font}, "
          f"{len(STYLE_NAMES)} styles)")


if __name__ == "__main__":
    main()
