#!/usr/bin/env python3
"""Scaffold a JasperReports Server UI theme overrides_custom.css from a palette.

A JRS UI theme is a folder under a Themes folder whose key file is
`overrides_custom.css` -- CSS that overrides the default UI look (banner, login,
buttons, toolbars). This emits a starter overrides_custom.css derived from the
SAME palette keys scaffold_jrxml.py uses (imported THEMES), so a deployed report
theme and the server UI theme can share one color story.

Deploy the result with deploy_theme.ps1 (-CssFile for a single override file, or
-ThemeDir for a folder of CSS + images). Themes take effect immediately; preview
by appending &theme=<name> to any JRS UI URL.

The selectors below cover the high-impact JRS chrome (banner, primary buttons,
login box, table headers). They are a STARTING POINT -- JRS ships a large default
theme; refine against your install's actual markup (deploy, then open the UI with
&theme=<name> and tweak). This script does not need the server.
"""
import argparse
import os

from scaffold_jrxml import THEMES, DEFAULT_THEME


def build_css(name: str, t: dict) -> str:
    header_bg = t["header_bg"] or "#2B3947"   # minimal theme has no header fill
    return f"""/* overrides_custom.css -- JRS UI theme '{name}'
   Generated by jasper-deploy scaffold_theme.py from the '{name}' palette.
   Deploy with: deploy_theme.ps1 -CssFile this.css -Name <theme>
   Preview:     append &theme=<theme> to any JRS UI URL. */

:root {{
    --jd-header-bg: {header_bg};
    --jd-header-fg: {t["header_fg"]};
    --jd-accent:    {t["title_fg"]};
    --jd-rule:      {t["rule"]};
}}

/* top banner / global header */
#banner, .banner, #frame > #banner {{
    background: var(--jd-header-bg) !important;
    color: var(--jd-header-fg) !important;
}}

/* primary buttons */
.button.primary, button.primary, .button.up.primary {{
    background: var(--jd-accent) !important;
    border-color: var(--jd-accent) !important;
    color: #FFFFFF !important;
}}

/* login page accent */
#loginBox .decorated.button, .loginForm .button.primary {{
    background: var(--jd-accent) !important;
}}

/* list / table headers */
.jr-mGrid-header, .dataTable thead th, .columnHeader {{
    background: var(--jd-header-bg) !important;
    color: var(--jd-header-fg) !important;
    border-bottom: 2px solid var(--jd-accent) !important;
}}

/* links / accent text */
a, .nav a, .menu .menuItem a {{
    color: var(--jd-accent);
}}
"""


def main():
    ap = argparse.ArgumentParser(description="Scaffold a JRS UI theme overrides_custom.css.")
    ap.add_argument("--name", required=True, help="theme name (used in the CSS header)")
    ap.add_argument("--palette", default=DEFAULT_THEME, choices=list(THEMES),
                    help=f"color palette shared with scaffold_jrxml --template (default {DEFAULT_THEME})")
    ap.add_argument("--out", help="output path (default: <name>/overrides_custom.css)")
    args = ap.parse_args()

    t = THEMES.get(args.palette, THEMES[DEFAULT_THEME])
    out_path = args.out or os.path.join(args.name, "overrides_custom.css")
    parent = os.path.dirname(os.path.abspath(out_path))
    os.makedirs(parent, exist_ok=True)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(build_css(args.name, t))
    print(f"wrote {out_path} (palette={args.palette})")
    print(f"deploy: deploy_theme.ps1 -CssFile {out_path} -Name {args.name}")


if __name__ == "__main__":
    main()
